# Insider Threat Detection System Configuration
# Copy this file to config.yaml and customize for your environment

# Database Configuration
database:
  path: "data/threat_detection.db"
  
# Data Collectors Configuration
collectors:
  # System Events Collector
  system_events:
    enabled: true
    database_path: "data/threat_detection.db"
    collection_interval: 30  # seconds
    
  # File Access Collector  
  file_access:
    enabled: true
    database_path: "data/threat_detection.db"
    collection_interval: 60  # seconds
    monitored_directories:
      # Add specific directories to monitor (optional)
      # - "C:/Users"
      # - "C:/Program Files"
      # - "/home"
      # - "/var/log"
    
  # Application Usage Collector
  app_usage:
    enabled: true
    database_path: "data/threat_detection.db"
    collection_interval: 45  # seconds

# Collection Intervals (seconds)
collection_intervals:
  system_events: 30
  file_access: 60
  app_usage: 45

# Real-time Processing Configuration
real_time:
  # Event queue settings
  queue_max_size: 1000
  batch_size: 10
  batch_timeout: 30  # seconds
  
  # Session management
  session_timeout: 3600  # seconds (1 hour)

# Anomaly Detection Engine Configuration
anomaly_engine:
  # Alert thresholds
  alert_threshold: 0.7
  high_alert_threshold: 0.9
  
  # Model weights for ensemble
  model_weights:
    isolation_forest: 0.6
    autoencoder: 0.4
  
  # Event processing
  queue_max_size: 1000
  batch_size: 10
  batch_timeout: 30
  
  # Pre-trained model paths (optional)
  # isolation_forest_model_path: "models/isolation_forest_model.joblib"
  # autoencoder_model_path: "models/autoencoder_model/"

# Machine Learning Models Configuration
ml_models:
  # Isolation Forest
  isolation_forest:
    n_estimators: 100
    contamination: 0.1
    max_samples: "auto"
    max_features: 1.0
    random_state: 42
    model_path: "models/"
    database_path: "data/threat_detection.db"
  
  # Autoencoder
  autoencoder:
    encoding_dim: 32
    hidden_layers: [64, 32]
    epochs: 100
    batch_size: 32
    learning_rate: 0.001
    validation_split: 0.2
    patience: 10
    anomaly_threshold: null  # Will be calculated automatically
    random_state: 42
    model_path: "models/"
    database_path: "data/threat_detection.db"

# Alert System Configuration
alerts:
  database_path: "data/threat_detection.db"
  
  # Email notifications
  email:
    enabled: false  # Set to true to enable email alerts
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    use_tls: true
    username: "your-email@gmail.com"
    password: "your-app-password"
    from_email: "security-alerts@yourcompany.com"
    recipients:
      - "security-team@yourcompany.com"
      - "soc-analyst@yourcompany.com"
    high_priority_recipients:
      - "security-manager@yourcompany.com"
      - "incident-response@yourcompany.com"

# Dashboard Configuration
dashboard:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: "your-secret-key-change-this-in-production"
  database_path: "data/threat_detection.db"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/insider_threat_detection.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Security Configuration
security:
  # Data encryption (if implemented)
  encrypt_sensitive_data: false
  encryption_key_file: "config/encryption.key"
  
  # Access control
  require_authentication: false
  allowed_ips: 
    - "127.0.0.1"
    - "::1"
  
# Performance Configuration
performance:
  # Database optimization
  sqlite_pragmas:
    journal_mode: "WAL"
    synchronous: "NORMAL"
    cache_size: -64000  # 64MB cache
    temp_store: "memory"
  
  # Processing limits
  max_events_per_batch: 100
  max_concurrent_collectors: 10
  memory_limit_mb: 1024

# Monitoring and Metrics
monitoring:
  # Enable performance monitoring
  enable_metrics: true
  metrics_interval: 300  # seconds (5 minutes)
  
  # Health check endpoint
  health_check_enabled: true
  health_check_port: 8080
  
# Data Retention Policies
retention:
  # Days to keep different types of data
  raw_events_days: 90
  processed_events_days: 180
  closed_alerts_days: 365
  user_profiles_days: 730  # 2 years
  
  # Cleanup schedule (cron format)
  cleanup_schedule: "0 2 * * *"  # Daily at 2 AM

# Integration Configuration
integrations:
  # SIEM integration
  siem:
    enabled: false
    type: "splunk"  # splunk, elastic, qradar
    endpoint: "https://your-siem.company.com:8088/services/collector"
    token: "your-siem-token"
    index: "insider_threats"
  
  # Ticketing system
  ticketing:
    enabled: false
    type: "jira"  # jira, servicenow
    url: "https://your-company.atlassian.net"
    username: "service-account"
    token: "your-api-token"
    project: "SEC"
    issue_type: "Security Incident"

# Development and Testing
development:
  # Generate synthetic data for testing
  synthetic_data: false
  synthetic_events_per_minute: 10
  synthetic_anomaly_rate: 0.05  # 5% of events are anomalous
  
  # Debug options
  debug_logging: false
  profiling_enabled: false
  test_mode: false